version: '3.8'
services:
  inventory-service:
    build: ./backend/inventory
    container_name: inventory-service
    ports:
      - "8001:8000"
    env_file:
      - ./backend/inventory/.env
    depends_on:
      - mongo
    networks:
      - app-network

  payment-service:
    build: ./backend/payment
    container_name: payment-service
    ports:
      - "8002:8000"
    env_file:
      - ./backend/payment/.env
    depends_on:
      - mongo
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
    depends_on:
      - inventory-service
      - payment-service
    networks:
      - app-network

  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge
