services:
  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"

  inventory-service:
    build: .
    container_name: inventory-service
    environment:
      - MONGO_URI=mongodb://mongo:27017/
    depends_on:
      - mongo
    ports:
      - "8000:8000"
